import Navbar from './components/navbar/Navbar';
import './globals.css';
import { Cairo } from 'next/font/google';

const font = Cairo({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='ar' dir='rtl' className='light antialiased'>
			<body className={font.className}>
				<Navbar />
				<main>{children}</main>
			</body>
		</html>
	);
}
